INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('LittleBigPlanet PS Vita','PlayStation Vita',9,'Platformer','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('LittleBigPlanet PS Vita -- Marvel Super Hero Edition','PlayStation Vita',9,'Platformer','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Splice: Tree of Life','iPad',8.5,'Puzzle','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('NHL 13','Xbox 360',8.5,'Sports','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('NHL 13','PlayStation 3',8.5,'Sports','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Total War Battles: Shogun','Macintosh',7,'Strategy','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Double Dragon: Neon','Xbox 360',3,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Guild Wars 2','PC',9,'RPG','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Double Dragon: Neon','PlayStation 3',3,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Total War Battles: Shogun','PC',7,'Strategy','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Tekken Tag Tournament 2','PlayStation 3',7.5,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Tekken Tag Tournament 2','Xbox 360',7.5,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Wild Blood','iPhone',7,NULL,'N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Mark of the Ninja','Xbox 360',9,'Action, Adventure','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Mark of the Ninja','PC',9,'Action, Adventure','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Home: A Unique Horror Adventure','Macintosh',6.5,'Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Home: A Unique Horror Adventure','PC',6.5,'Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Avengers Initiative','iPhone',8,'Action','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Way of the Samurai 4','PlayStation 3',5.5,'Action, Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('JoJo''s Bizarre Adventure HD','Xbox 360',7,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('JoJo''s Bizarre Adventure HD','PlayStation 3',7,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Mass Effect 3: Leviathan','Xbox 360',7.5,'RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Mass Effect 3: Leviathan','PlayStation 3',7.5,'RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Mass Effect 3: Leviathan','PC',7.5,'RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Dark Souls (Prepare to Die Edition)','PC',9,'Action, RPG','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Symphony','PC',7,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Bastion','iPad',9,'Action, RPG','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Tom Clancy''s Ghost Recon Phantoms','PC',7.5,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Thirty Flights of Loving','PC',8,'Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Legasista','PlayStation 3',6.5,'Action, RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('The Walking Dead: The Game -- Episode 3: Long Road Ahead','Macintosh',9,'Adventure','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('World of Warcraft: Mists of Pandaria','PC',8.7,'RPG','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Hell Yeah! Wrath of the Dead Rabbit','PlayStation 3',4.9,'Platformer','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Pokemon White Version 2','Nintendo DS',9.6,'RPG','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('War of the Roses','PC',7.3,'Action','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Pokemon Black Version 2','Nintendo DS',9.6,'RPG','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Drakerider','iPhone',6.5,'RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('The Walking Dead: The Game -- Episode 3: Long Road Ahead','Xbox 360',9,'Adventure','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('The Walking Dead: The Game -- Episode 3: Long Road Ahead','PC',9,'Adventure','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('The Walking Dead: The Game -- Episode 3: Long Road Ahead','PlayStation 3',9,'Adventure','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Rock Band Blitz','Xbox 360',8.5,'Music','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Counter-Strike: Global Offensive','Macintosh',8,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Worms Revolution','PlayStation 3',8.5,'Strategy','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Worms Revolution','PC',8.5,'Strategy','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Worms Revolution','Xbox 360',8.5,'Strategy','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Bad Piggies','iPhone',9.2,'Action','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Resident Evil 6','PlayStation 3',7.9,'Action, Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Resident Evil 6','Xbox 360',7.9,'Action, Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Shad''O','PC',7,'Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Demon''s Score','iPhone',6.9,'Action','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('NBA 2K13','Xbox 360',9.1,'Sports','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Counter-Strike: Global Offensive','PC',8,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('The World Ends with You: Solo Remix','iPad',9.5,'RPG','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Counter-Strike: Global Offensive','PlayStation 3',8,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('The World Ends with You: Solo Remix','iPhone',9.5,'RPG','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Counter-Strike: Global Offensive','Xbox 360',8,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Madden NFL 13','PlayStation Vita',6,'Sports','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Madden NFL 13','PlayStation 3',9,'Sports','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Madden NFL 13','Xbox 360',9,'Sports','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Hoodwink','PC',2.5,'Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('NBA 2K13','PlayStation 3',9.1,'Sports','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('NBA 2K13','PC',9.1,'Sports','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Lili: Child of Geos','iPhone',7,'Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Marvel vs. Capcom Origins','Xbox 360',8.2,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Marvel vs. Capcom Origins','PlayStation 3',8.2,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Dead or Alive 5','PlayStation 3',8.8,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Dead or Alive 5','Xbox 360',8.8,'Fighting','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Medal of Honor Warfighter','PC',4,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Professor Layton and the Miracle Mask','Nintendo 3DS',8.7,'Adventure','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Hotline Miami','PC',8.8,'Action','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Edna & Harvey: Harvey''s New Eyes','PC',6,'Adventure','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Medal of Honor Warfighter','PlayStation 3',4,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Medal of Honor Warfighter','Xbox 360',4,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Transformers: Fall of Cybertron','Xbox 360',8.5,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Transformers: Fall of Cybertron','PlayStation 3',8.5,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Hero Academy','PC',9,'Board','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Hero Academy','iPhone',9,'Strategy','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Puzzle Craft','iPhone',9,'Puzzle','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Realms Of Ancient War','Xbox 360',5.5,'Action','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Realms Of Ancient War','PlayStation 3',5.5,'Action','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Anomaly: Warzone Earth','PlayStation 3',8.2,'Action','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Darksiders II','PC',7.5,'Action','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Left 4 Dead 2: Cold Stream','Macintosh',7,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Left 4 Dead 2: Cold Stream','PC',7,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Puzzle Craft','Android',9,'Puzzle','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Left 4 Dead 2: Cold Stream','Xbox 360',7,'Shooter','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Horn','iPhone',9,'Action, Adventure','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Forza Horizon','Xbox 360',9,'Racing','Y');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('FIFA Soccer 13','PlayStation Vita',4,'Sports','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Mugen Souls','PlayStation 3',3.9,'Strategy, RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Crazy Taxi','iPhone',7.1,'Racing, Action','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('New Little King''s Story','PlayStation Vita',5.8,'RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Fable: The Journey','Xbox 360',7.2,'Action, RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('The Lord of the Rings Online: Riders of Rohan','PC',8.3,'RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Doom 3: BFG Edition','Xbox 360',7.6,'RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Rugby League Live 2','Xbox 360',6,'Sports','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Rugby League Live 2','PlayStation 3',6,'Sports','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Doom 3: BFG Edition','PlayStation 3',7.6,'RPG','N');
INSERT INTO game(title,platform,score,genre,editors_choice) VALUES ('Punch Quest','iPhone',9.3,'Action','Y');
